Update testing

diff --git a/.github/workflows/student_management.yml b/.github/workflows/student_management.yml
--- a/.github/workflows/student_management.yml
+++ b/.github/workflows/student_management.yml
@@ -28,103 +28,103 @@ jobs:
       with:
         name: build
         path: build
-# deploys:
-#   needs: build
-#   runs-on: ubuntu-latest
+deploys:
+  needs: build
+  runs-on: ubuntu-latest
 
-#   steps:
-#     - name: Get the Production Artifact
-#         uses: actions/download-artifact@v2
-#         with:
-#           name: build
-#           path: build
-#     - name: Add SSH Key
-#         uses: webfactory/ssh-agent@v0.5.3
-#         with:
-#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+  steps:
+    - name: Get the Production Artifact
+        uses: actions/download-artifact@v2
+        with:
+          name: build
+          path: build
+    - name: Add SSH Key
+        uses: webfactory/ssh-agent@v0.5.3
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-#     - name: Ensure target directory exists
-#         uses: appleboy/ssh-action@master
-#         with:
-#           host: ${{ secrets.EC2_IP }}
-#           username: ${{ secrets.EC2_USERNAME }}
-#           key: ${{ secrets.SSH_PRIVATE_KEY }}
-#           port: 22
-#           script: |
-#             mkdir -p /home/ubuntu/app
-#             chown -R ubuntu:ubuntu /home/ubuntu/app
+    - name: Ensure target directory exists
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.EC2_IP }}
+          username: ${{ secrets.EC2_USERNAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          port: 22
+          script: |
+            mkdir -p /home/ubuntu/app
+            chown -R ubuntu:ubuntu /home/ubuntu/app
 
-#     - name: Copy files to EC2
-#       uses: appleboy/scp-action@master
-#       with:
-#         host: ${{ secrets.EC2_IP }}
-#         username: ${{ secrets.EC2_USERNAME }}
-#         key: ${{ secrets.SSH_PRIVATE_KEY }}
-#         port: 22
-#         source: "build/*"
-#         target: "/home/ubuntu/app/"
+    - name: Copy files to EC2
+      uses: appleboy/scp-action@master
+      with:
+        host: ${{ secrets.EC2_IP }}
+        username: ${{ secrets.EC2_USERNAME }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        port: 22
+        source: "build/*"
+        target: "/home/ubuntu/app/"
 
-#     - name: Create .env file
-#       uses: appleboy/ssh-action@master
-#       with:
-#         host: ${{ secrets.EC2_IP }}
-#         username: ${{ secrets.EC2_USERNAME }}
-#         key: ${{ secrets.SSH_PRIVATE_KEY }}
-#         port: 22
-#         script: |
-#           cat <<EOF > /home/ubuntu/app/build/configs/.env.staging
-#           NODE_ENV=${{ secrets.NODE_ENV }}
-#           PORT=${{ secrets.PORT }}
-#           LOG_LEVEL=${{ secrets.LOG_LEVEL }}
-#           MONGODB_URL=${{ secrets.MONGODB_URL}}
-#           EOF
+    - name: Create .env file
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.EC2_IP }}
+        username: ${{ secrets.EC2_USERNAME }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        port: 22
+        script: |
+          cat <<EOF > /home/ubuntu/app/build/configs/.env.staging
+          NODE_ENV=${{ secrets.NODE_ENV }}
+          PORT=${{ secrets.PORT }}
+          LOG_LEVEL=${{ secrets.LOG_LEVEL }}
+          MONGODB_URL=${{ secrets.MONGODB_URL}}
+          EOF
 
-#     - name: Start Application
-#       uses: appleboy/ssh-action@master
-#       with:
-#         host: ${{ secrets.EC2_IP }}
-#         username: ${{ secrets.EC2_USERNAME }}
-#         key: ${{ secrets.SSH_PRIVATE_KEY }}
-#         port: 22
-#         script: |
-#           #!/bin/bash
+    - name: Start Application
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{ secrets.EC2_IP }}
+        username: ${{ secrets.EC2_USERNAME }}
+        key: ${{ secrets.SSH_PRIVATE_KEY }}
+        port: 22
+        script: |
+          #!/bin/bash
 
-#           # Check if nvm is installed
-#           if [ -s "$HOME/.nvm/nvm.sh" ]; then
-#             source "$HOME/.nvm/nvm.sh"
-#           elif [ -s "/usr/local/nvm/nvm.sh" ]; then
-#             source "/usr/local/nvm/nvm.sh"
-#           else
-#             echo "nvm is not installed."
-#             exit 1
-#           fi
+          # Check if nvm is installed
+          if [ -s "$HOME/.nvm/nvm.sh" ]; then
+            source "$HOME/.nvm/nvm.sh"
+          elif [ -s "/usr/local/nvm/nvm.sh" ]; then
+            source "/usr/local/nvm/nvm.sh"
+          else
+            echo "nvm is not installed."
+            exit 1
+          fi
 
-#           # Verify yarn installation
-#           if ! command -v yarn &> /dev/null; then
-#             echo "Yarn could not be found"
-#             exit 1
-#           fi
+          # Verify yarn installation
+          if ! command -v yarn &> /dev/null; then
+            echo "Yarn could not be found"
+            exit 1
+          fi
 
-#           cd /home/ubuntu/app/build
-#           echo "Checking directory contents..."
-#           ls -alh # Lists all files in the current directory
+          cd /home/ubuntu/app/build
+          echo "Checking directory contents..."
+          ls -alh # Lists all files in the current directory
 
-#           # Check if server.js exists in the correct directory
-#           if [ ! -f ./src/server.js ]; then
-#             echo "server.js not found in ./src/"
-#             exit 1
-#           fi
+          # Check if server.js exists in the correct directory
+          if [ ! -f ./src/server.js ]; then
+            echo "server.js not found in ./src/"
+            exit 1
+          fi
 
-#           # Install Dependencies
-#           echo "Installing dependencies..."
-#           yarn install
+          # Install Dependencies
+          echo "Installing dependencies..."
+          yarn install
 
-#           # Check if the PM2 process is running
-#           if pm2 show student > /dev/null; then
-#             echo "Application is running. Restarting..."
-#             pm2 restart student
-#           else
-#             echo "Application is not running. Starting..."
-#             pm2 start ./src/server.js --name student
-#           fi
+          # Check if the PM2 process is running
+          if pm2 show student > /dev/null; then
+            echo "Application is running. Restarting..."
+            pm2 restart student
+          else
+            echo "Application is not running. Starting..."
+            pm2 start ./src/server.js --name student
+          fi
   
